version: "3"
services:
  mycache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ~/redis-data:/data
    restart: always
    command: redis-server --requirepass test

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161"
    restart: always

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "4150:4150"
      - "4151:4151"
    restart: always
    depends_on:
      - nsqlookupd

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"
    restart: always
    depends_on:
      - nsqlookupd
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ~/grafana-storage:/var/lib/grafana
    restart: always

  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ~/promo/:/etc/prometheus/
      - ~/prometheus_data/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9070:9090"
    restart: always